var current_culture = "en-US";
var culture = {
    lang: "中",
    all: "All",
    username: "Username",
    password: "Password",
    login: "Login",
    username_required: "Username Required!",
    password_required: "Password Required!",
    login_fault: "Login Fault",
    user: "User",
    login_out: "LogOut",

    overview: "Overview",
    handlers: "Handlers",
    tasks: "Tasks",
    task:"Task",
    resources: "Resources",
    logs: "Logs",
    config: "Config",
    users: "Users",
    update: "Update",

    last_update: "Last update",
    every: "every",
    never: "never",
    seconds: "seconds",
    minutes: "minutes",

    count_by_date: "Task and Resource Count by date",
    total: "Totals",
    last: "last",
    month: "month",
    year: "year",
    count_by_app: "Count by AppName",

    image: "Image",
    video: "Video",
    attachment: "Attachment",

    no_data:"no data",
    handlerId: "HandlerId",
    machineName: "MachineName",
    total_task_count: "TaskTotal",
    state: "State",
    startTime: "StartTime",
    endTime: "EndTime",
    empty: "Empty",

    of:"of",
    page: "Page",
    filter: "Filter",
    page_size_up: "Page size up to",
    next_page: "next page",
    last_page: "last page",

    fileId:"FileId",
    fileName:"FileName",
    handler:"Handler",
    percent:"Percent",
    createTime: "CreateTime",
    completedTime: "CompletedTime",
    view: "View",
    reDo: "ReDo",

    outputFormat: "OutputFormat",
    default:"Default",
    flag: "flag",
    model: "Model",
    scale: "Scale",
    cut: "Cut",
    by_width: "By Width",
    by_height: "By Height",
    width:"Width",
    height: "Height",

    quality: "Quality",
    original: "Original",
    lower: "Lower",
    medium: "Medium",
    bad: "Bad",

    size: "Size",
    uploadDate: "UploadDate",
    from: "From",
    fileType: "FileType",
    dol: "Dol",
    del: "Del",
    add: "Add",
    unknow:"unknow",

}