var current_culture = "zh-CN";
var culture = {
    lang: "EN",
    all: "所有",
    username: "用户名",
    password: "密码",
    login: "登陆",
    username_required: "用户名是必填项！",
    password_required: "密码是必填项！",
    login_fault: "登陆失败",
    user: "用户",
    login_out: "退出",
    description: "描述",

    overview: "概况统计",
    handlers: "处理器",
    tasks: "转换任务",
    task: "任务",
    file: "文件",
    task_count: "任务总数",
    resources: "资源列表",
    resource: "资源",
    resource_count: "资源总数",
    logs: "操作日志",
    log: "日志",
    configs: "配置管理",
    config: "配置",
    users: "用户管理",
    update: "更新",
    save: "保存",
    create: "创建",

    last_update: "上次更新",
    every: "每",
    never: "从不",
    seconds: "秒",
    minutes: "分钟",

    count_by_date: "根据时间统计",
    totals: "总数",
    total: "总数",
    last: "最近",
    month: "月",
    year: "年",
    count_by_app: "应用程序总数",
    resource_task_count_by_appname: "资源和任务总数",
    resource_task_count_by_date: "资源和任务总数",
    download_count_by_date: "下载量",
    resource_count_by_appname: "资源总数",
    task_count_by_appname: "任务总数",

    image: "图片",
    video: "视频",
    audio:"音频",
    office:"文档",
    pdf: "pdf",
    text:"文本",
    attachment: "附件",

    no_data: "无数据",
    handlerId: "处理器编号",
    machineName: "机器名",
    total_task_count: "任务总数",
    state: "状态",
    startTime: "启动时间",
    endTime: "结束时间",
    empty: "清空",

    of: "/",
    page: "页",
    filter: "过滤",
    page_size_up: "每页个数",
    next_page: "下一页",
    last_page: "上一页",

    fileId: "文件编号",
    fileName: "文件名称",
    handler: "处理器",
    percent: "百分比",
    createTime: "创建时间",
    completedTime: "完成时间",
    view: "预览",
    reDo: "重做",
    operation: "操作",

    outputFormat: "输出格式",
    format: "格式",
    default: "默认",
    flag: "标识",
    model: "模式",
    convertModel: "转换模式",
    scale: "缩放",
    cut: "剪切",
    by_width: "按宽度",
    by_height: "按高度",
    by_quality: "按质量",
    width: "宽度",
    height: "高度",
    image_quality: "图片质量",
    high: "高",
    low: "低",

    quality: "质量",
    original: "原画",
    lower: "稍低",
    medium: "中等",
    bad: "差",

    size: "大小",
    uploadTime: "上传时间",
    deleteTime: "删除时间",
    from: "来源",
    owner: "所有者",
    fileType: "文件类型",
    dol: "下载",
    download: "下载",
    downloads: "下载量",
    del: "删除",
    permanent_del: "永久删除",
    add: "添加",
    unknow: "未知",
    ok: "确定",
    upload: "上传",
    no_file_select: " 未选中文件",
    convert: "转换",
    type: "类型",

    thumbnails: "缩略图列表",
    m3u8List: "M3u8列表",
    fileList: "子文件列表",
    m3u8Id: "M3u8编号",
    duration: "持续时间",
    ts: "切片数",
    cp: "截图数",
    thumbnailId: "缩略图编号",

    id: "编号",
    appName: "应用程序",
    applicationName: "应用程序名称",
    application: "应用程序",
    taskId: "任务编号",
    content: "内容",

    extension: "扩展名",
    action: "行为",
    delete: "删除",
    deleting: "删除中",

    role: "角色",
    password_not_match: "密码不匹配",
    invalid_password: "密码不正确",
    confirm: "确认",
    auth_code: "认证编码",

    department: "部门",
    department_right: "部门权限",
    department_name: "部门名称",
    modified: "已修改",
    order: "顺序",
    layer: "层级",
    add_top_department: "添加顶层部门",
    add_sub_department: "添加子部门",
    update_department: "修改部门",
    department_code: "部门编码",
    parent_code: "上级编码",
    delete_department: "删除部门",
    detail_department: "部门详情",
    company: "公司",
    name: "名称",
    management: "管理",
    code: "编码",

    access_authority: "访问权限",
    empty_access: "清空权限",
    change_access: "修改权限",
    authority_type: "权限类型",
    only_current: "仅当前",
    current_and_sub: "当前及下属",
    current_and_sup: "当前及上级",
    end: "结尾",

    process_count: "处理次数",
    save_success: "保存成功",
    shared: "分享",
    day: "天",
    valid_period: "有效时间",
    expired_date: "过期时间",
    shared_link: "分享链接",
    shared_type: "分享形式",
    public: "公开",
    encrypt: "加密",
    never_expire: "永久有效",

    please_input_shared_password: "请输入共享密码",
    link_expired: "链接已过期",
    link_disabled: "链接已被禁用",
    file_converting: "文件转换中...",
    not_support_preview: "不支持预览",
    date: "时间",
    used: "可用",
    disabled: "禁用",

    cache_file: "缓存文件",
    cache_file_location: "缓存文件位置",
    cache_file_status: "缓存文件状态",
    deleted: "已删除",
    exists: "存在",
    empty_cache_file: "清除缓存文件",
    user_agent: "用户代理",
    restore_file: "恢复文件",
    recycle_bin: "文件回收站",
    date_range: "时段",
    from1: "从",
    to: "到",
    servers: "服务器",
    web_server: "Web服务器",
    server_name: "服务器名称",
    os: "操作系统",
    memory: "内存",
    disk: "磁盘",
    cacheFiles: "缓存文件",
    logFiles: "日志文件",
    route_server: "路由服务器",
    port: "端口",
    version: "版本",
    data_server: "数据服务器",
    data: "数据",
    available: "可用",
    upTime: "运行时间",
    startup: "启动中",
    image_convert: "图片转换",
    video_convert: "视频转换",
    playtime: "播放记录",
    replace: "替换",
    history: "历史记录",
    replaceTime: "替换时间",
    monitorList: "监视列表",
    monitorPath: "监视路径",
    monitorState: "监视状态",
    monitorTime: "监视时间",
    monitorMachine: "监视机器",
    contentType: "内容类型",

    wait: "等待中",
    processing: "处理中",
    completed: "已完成",
    updated: "已更新",
    error: "已出错"
}