var current_culture = "zh-CN";
var culture = {
    lang: "EN",
    all: "所有",
    username: "用户名",
    password: "密码",
    login: "登陆",
    username_required: "用户名是必填项！",
    password_required: "密码是必填项！",
    login_fault: "登陆失败",
    user: "用户",
    login_out: "退出",

    overview: "概况统计",
    handlers: "处理器",
    tasks: "转换任务",
    task: "任务",
    resources: "资源列表",
    resource: "资源",
    logs: "操作日志",
    log: "日志",
    configs: "配置管理",
    config: "配置",
    users: "用户管理",
    update: "更新",
    save: "保存",

    last_update: "上次更新",
    every: "每",
    never: "从不",
    seconds: "秒",
    minutes: "分钟",

    count_by_date: "根据时间统计任务和资源个数",
    totals: "总数",
    total: "总数",
    last: "最近",
    month: "月",
    year: "年",
    count_by_app: "根据应用程序总数",

    image: "图片",
    video: "视频",
    attachment: "附件",

    no_data: "无数据",
    handlerId: "处理器编号",
    machineName: "机器名",
    total_task_count: "任务总数",
    state: "状态",
    startTime: "启动时间",
    endTime: "结束时间",
    empty: "清空",

    of: "/",
    page: "页",
    filter: "过滤",
    page_size_up: "每页个数",
    next_page: "下一页",
    last_page: "上一页",

    fileId: "文件编号",
    fileName: "文件名称",
    handler: "处理器",
    percent: "百分比",
    createTime: "创建时间",
    completedTime: "完成时间",
    view: "预览",
    reDo: "重做",

    outputFormat: "输出格式",
    format: "格式",
    default: "默认",
    flag: "标识",
    model: "模式",
    scale: "缩放",
    cut: "剪切",
    by_width: "按宽度",
    by_height: "按高度",
    width: "宽度",
    height: "高度",

    quality: "质量",
    original: "原画",
    lower: "稍低",
    medium: "中等",
    bad: "差",

    size: "大小",
    uploadDate: "上传时间",
    from: "来源",
    fileType: "文件类型",
    dol: "下载",
    del: "删除",
    add: "添加",
    unknow: "未知",
    ok: "确定",
    upload: "上传",
    no_file_select: " 未选中文件",
    convert: "转换",
    type: "类型",

    thumbnails: "缩略图列表",
    m3u8List: "M3u8列表",
    fileList: "子文件列表",
    m3u8Id: "M3u8编号",
    duration: "持续时间",
    ts: "切片数",
    cp: "截图数",
    thumbnailId: "缩略图编号",

    id: "编号",
    appName: "应用程序",
    applicationName: "应用程序名称",
    application: "应用程序",
    taskId: "任务编号",
    content: "内容",
    user: "用户",

    extension: "扩展名",
    action: "行为",
    delete: "删除",

    role: "角色",
    password_not_match: "密码不匹配",
    confirm: "确认",
    auth_code: "认证编码",

    department: "部门",
    department_right: "部门权限",
    department_name: "部门名称",
    modified: "已修改",
    order: "顺序",
    layer: "层级",
    add_top_department: "添加顶层部门",
    add_sub_department: "添加子部门",
    update_department: "修改部门",
    department_code: "部门编码",
    parent_code: "上级编码",
    delete_department: "删除部门",
    detail_department: "部门详情",
    do_not_delete_topnode:"顶层节点无法删除",
}