var current_culture = "en-US";
var culture = {
    lang: "中",
    all: "All ",
    username: "Username",
    password: "Password",
    login: "Login",
    username_required: "Username Required!",
    password_required: "Password Required!",
    login_fault: "Login Fault",
    user: "User",
    login_out: "LogOut",

    overview: "Overview",
    handlers: "Handlers",
    tasks: "Tasks",
    task: "Task",
    task_count:"TaskCount",
    resources: "Resources",
    resource: "Resources",
    resource_count:"ResourceCount",
    logs: "Logs",
    log: "Log",
    configs: "Config",
    config: "Config",
    users: "Users",
    update: "Update ",
    save: "Save",
    create: "Create",

    last_update: "Last update",
    every: "every",
    never: "never",
    seconds: "seconds",
    minutes: "minutes",

    count_by_date: "Task and Resource Count by date",
    totals: "Totals",
    total: "Total",
    last: "last",
    month: "month",
    year: "year",
    count_by_app: "Count by AppName",

    image: "Image",
    video: "Video",
    attachment: "Attachment",

    no_data: "no data",
    handlerId: "HandlerId",
    machineName: "MachineName",
    total_task_count: "TaskTotal",
    state: "State",
    startTime: "StartTime",
    endTime: "EndTime",
    empty: "Empty",

    of: "of",
    page: "Page",
    filter: "Filter",
    page_size_up: "Page size up to",
    next_page: "next page",
    last_page: "last page",

    fileId: "FileId",
    fileName: "FileName",
    handler: "Handler",
    percent: "Percent",
    createTime: "CreateTime",
    completedTime: "CompletedTime",
    view: "View",
    reDo: "ReDo",

    outputFormat: "OutputFormat",
    format: "Format",
    default: "Default",
    flag: "flag",
    model: "Model",
    scale: "Scale",
    cut: "Cut",
    by_width: "By Width",
    by_height: "By Height",
    width: "Width",
    height: "Height",

    quality: "Quality",
    original: "Original",
    lower: "Lower",
    medium: "Medium",
    bad: "Bad",

    size: "Size",
    uploadDate: "UploadDate",
    from: "From",
    owner: "Owner",
    fileType: "FileType",
    dol: "Dol",
    del: "Del",
    add: "Add ",
    unknow: "unknow",
    ok: "Ok",
    upload: "Upload",
    no_file_select: " no file selected",
    convert: "Convert",
    type: "Type",

    thumbnails: "Thumbnails",
    m3u8List: "M3u8List",
    fileList: "FileList",
    m3u8Id: "M3u8Id",
    duration: "Duration",
    ts: "Ts",
    cp: "Cp",
    thumbnailId: "ThumbnailId",

    id: "Id",
    appName: "AppName",
    applicationName: "ApplicationName",
    application: "Application",
    taskId: "TaskId",
    content: "Content",

    extension: "Extension",
    action: "Action",
    delete: "Delete",

    role: "Role",
    password_not_match: "PassWord not matched",
    confirm: "confirm",
    invalid_password: "Invalid Password",
    auth_code: "AuthCode",

    department: "Department",
    department_right: "DepartmentACL",
    department_name: "DepartmentName",
    modified: "Modified",
    order: "Order",
    layer: "Layer",
    add_top_department: "Add Top Department",
    add_sub_department: "Add Sub Department",
    update_department: "Update Department",
    department_code: "DepartmentCode",
    parent_code: "ParentCode",
    delete_department: "Delete Department",
    detail_department: "Department Detail",
    company: "Company",
    name: "Name",
    management: "Management",
    code: "Code",

    access_authority: "AccessAuthority",
    change_access: "ChangeAccess",
    empty_access: "EmptyAccess",
    authority_type: "AuthorityType",
    only_current: "Current",
    current_and_sub: "Current&Sub",
    current_and_sup: "Current&Sup",
    end: "End",

    process_count: "ProCount",
    save_success: "Save Success",
    shared: "Shared",
    day: "Day",
    valid_period: "Valid Period",
    expired_date: "ExpiredDate",
    shared_link: "SharedLink",
    shared_type: "SharedType",
    public: "Public",
    encrypt: "Encrypt",
    never_expire: "Never Expires",

    please_input_shared_password: "Please Input Shared Password",
    link_expired: "Link expired",
    link_disabled:"Link Disabled",
    file_converting: "File Converting...",
    not_support_preview: "Not Supported Preview",
    date: "Date",
    used: "Used",
    disabled: "Disabled",

    cache_file: "CacheFile",
    cache_file_location: "CacheFileLocation",
    cache_file_status: "CacheFileStatus",
    deleted: "Deleted",
    exists: "Exists",
    empty_cache_file:"EmptyCacheFile"
}